### ISSUE TITLE
CONTRIBUTING.md has no meta file [v1.0.16]

### ISSUE THREAD

**Issue by PavelKlym** [StansAssets/com.stansassets.foundation#70]
![image](https://user-images.githubusercontent.com/13795723/102695266-cbcbec00-422e-11eb-8c03-ad85ddbbb428.png)
![image](https://user-images.githubusercontent.com/13795723/102695350-61677b80-422f-11eb-9748-282e7c57f2d0.png)

**Comment by PavelKlym** [comment]
As dependency of Dev Kit 1.0.1

**Comment by stan-osipov** [comment]
fixed:
https://github.com/StansAssets/com.stansassets.foundation/commit/1dfdfbe2975e71049bc3bdb695140ce6c399d93d
