### ISSUE TITLE
MainThreadDispatcher bug?

### ISSUE THREAD

**Issue by STARasGAMES** [StansAssets/com.stansassets.foundation#78]
Hi
I'm just reading code and I think there is a bug in MainThreadDispatcherBase.cs
https://github.com/StansAssets/com.stansassets.foundation/blob/master/Runtime/Async/MainThreadDispatcher/MainThreadDispatcherBase.cs
In line 16 it should be ```while``` instead of ```if```.

**Comment by Yurii-Tor** [comment]
Agree. This one becomes a problem if the queue is overfilled between frames but usually, in common cases, it doesn't (EX: scanning QR code 2-10 times per second)

**Comment by stan-osipov** [comment]
Yup, `while` would make sence. I wonder if we did this to time slice the load. But since not comments is there, I think we should just change it while. Thanks @STARasGAMES
